name: Build and Deploy

on:
  push:
    branches:
      - main  # Deploy when pushing to experiment branch
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test-unit

      - name: Run unit tests (addons)
        run: npm run test-unit-addons

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build three.js
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            build/
            editor/
            examples/
            docs/
            manual/
            playground/
          retention-days: 7

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/experiment'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build three.js
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Create deployment directory
        run: |
          mkdir -p _site
          cp -r build _site/
          cp -r editor _site/
          cp -r examples _site/
          cp -r docs _site/
          cp -r manual _site/
          cp -r playground _site/
          cp README.md _site/
          echo '# Rob Higgins Enhanced Three.js Fork' > _site/index.md
          echo 'Visit the [Enhanced Editor](./editor/) or browse [Examples](./examples/)' >> _site/index.md

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
