name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Only fetch latest commit (saves ~2.5 minutes)

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests (core)
        run: npm run test-unit

      - name: Run unit tests (addons)
        run: npm run test-unit-addons

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: |
          ls -lh build/
          echo "✅ Build completed successfully"

      - name: Comment on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ job.status }}';
            const emoji = status === 'success' ? '✅' : '❌';
            const message = `${emoji} **Build ${status}**\n\nLint and tests have ${status === 'success' ? 'passed' : 'failed'}.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
